name: API Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Newman
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run API tests
        run: |
          mkdir -p report
          newman run "Api tests.postman_collection.json" \
            -e "reqres.postman_environment.json" \
            -r cli,htmlextra \
            --reporter-htmlextra-export report/index.html

      - name: Upload test report
        if: always() # даже если тесты упали
        uses: actions/upload-pages-artifact@v3
        with:
          path: report

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        if: always()
        uses: actions/deploy-pages@v4